[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
optimizer = true
optimizer_runs = 100
build_info = true
solc = "0.8.19"
# eth-rpc-url = "https://sepolia.infura.io/v3/"
# etherscan_api_key = "YOURETHERSCANAPIKEY"

[profile.ci]
verbosity = 4


[fmt]
line_length = 160
tab_width = 4
bracket_spacing = true


# See more config options https://github.com/foundry-rs/foundry/tree/master/config
